### ISSUE TITLE
Cannot validate certificate for imap server

### ISSUE THREAD

**Issue by jprusch** [mattermost/mattermost-plugin-email-reply#12]
Hi,
doing some tests with the plugin, I get the following error no matter what type of security I chose for the IMAP server (None, SSL, TLS). Port is specified as :143 (None) or 993 (TLS/SSL)
`
2020-04-07T08:32:33.716+0200    error   mlog/sugar.go:23        Failed to poll mailbox{"plugin_id": "com.mattermost.mailermost-plugin", "error": "failure connecting to IMAP server: x509: cannot validate certificate for 192.168.2.13 because it doesn't contain any IP SANs"}
`
Why is a x509 check taking place on an unsecured imap access?

**Comment by mkraft** [comment]
@jprusch It looks like the `(*Poller).security` field isn't used anywhere, so the configuration setting (`None`, `SSL`, or `TLS`) is unused. All options [use the go-imap's `client.DialTLS` function](https://github.com/mattermost/mattermost-plugin-email-reply/blob/master/server/mailermost/mailermost.go#L78). Would you be interested in submitting a pull request to fix this?

**Comment by jprusch** [comment]
Well, I can read a log & do some testing, but I'm not a Go dev guy (although I'd like to be one...)

**Comment by jprusch** [comment]
Seems to be solved when using a FQDN instead of an IP address.

**Comment by shihanng** [comment]
I can work in this if that okay. I recently worked on #21 so totally understand if you want to leave this for another new contributor.

**Comment by hanzei** [comment]
Sure, thanks would be great @shihanng. All yours!

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,

ich bin vom 12.10.2020  bis zum 01.11.2020  nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.

Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.

In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de).
Mit freundlichen Grüßen
i.V. Jan-Peter RuschTEL +49 (0)571-502-145
j.rusch@schaeferbarthold.de

______________________________________________________________________

Schäferbarthold GmbHErbeweg 2-12 | 32457 Porta Westfalica | Deutschlandwww.schaeferbarthold.de


Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold








Closed #12 via #23.

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/mattermost/mattermost-plugin-email-reply/issues/12#event-3903419365
